use streamcart;

-- Revenue KPI
-- Revenue = Net sales value generated from completed orders after discounts.
 select
 round(sum(quantity * unit_price * (1 - discount_pct/100)), 2) as total_revenue
 from orders
 where return_status = 'Completed';
 
 -- Gross Profit
 -- Profit generated after product cost deduction.
select
round(sum((p.selling_price - p.cost_price) * o.quantity), 2) as gross_profit
from orders o
join products p 
on o.product_id = p.product_id
where o.return_status = 'Completed';

-- Average Order value
-- Average revenue generated per completed order.
select
round(sum(quantity * unit_price * (1-discount_pct/100)) / count(distinct order_id), 2) as average_order_value
from orders
where return_status = 'Completed';

-- CUSTOMER LIFETIME VALUE 
-- Total revenue generated by a customer across all completed orders.
select 
customer_id,
round(sum(quantity * unit_price * (1-discount_pct/100)), 2) as customer_lifetime_value
from orders
where return_status = 'Completed'
group by customer_id
order by customer_lifetime_value desc;

-- SUBSCRIPTION REVENUE- RECURRING REVENUE GENERATED THROUGH SUBSCRIPTIONS
select 
round(sum(monthly_fee), 2) as subscription_revenue
from subscriptions;

-- AVERAGE CSAT
select
round(avg(csat_score), 2) as average_csat
from support_tickets;

-- SLA BREACH RATE- PERCENTAGE OF TICKETS VIOLATING SLA TARGETS.
with sla_data as(
	select
    case
    when priority = 'Critical' and datediff(resolved_date, created_date)>1 then 1
    when priority = 'High' and datediff(resolved_date, created_date)>3 then 1
    when priority= 'Medium' and datediff(resolved_date, created_date)>7 then 1
    else 0
    end as breached
    from support_tickets
    where resolved_date is not null
    )
    
select
round(100 * sum(breached) / count(*), 2) as sla_breach_rate
from sla_data;

-- MONTHLY RECURRING REVENUE- predictable monthly revenue generated from active subscription plans.
with latest_order_date as
(		select max(order_date) as max_date
		from orders
)

select
round(sum(monthly_fee), 2) as monthly_recurring_revenue
from subscriptions s
cross join latest_order_date l
where s.end_date > l.max_date;

-- ACTIVE CUSTOMERS- WHO HAVE PLACED A COMPLETED ORDER WITHIN LAST 90 DAYS
with max_order_date as
(
	select max(order_date) as latest_order_date
	from orders
)

select 
count(distinct customer_id) as active_customers
from orders
cross join max_order_date m
where return_status = 'Completed'
and order_date >= date_sub(m.latest_order_date, interval 90 day);

-- CHURN CUSTOMERS - NO ORDERS WITHIN LAST 180 DAYS FROM LAST AVAILABLE DATE
with max_order_date as
(
	select max(order_date) as latest_order_date
    from orders
),

customer_last_order as
(
	select customer_id,
    max(order_date) as last_order
    from orders
    where return_status = 'Completed'
    group by customer_id
)

select count(*) as churned_customers
from customer_last_order c
cross join max_order_date m 
where datediff(m.latest_order_date, c.last_order) > 180;

-- CHURN RATE PERCENT
with max_order_date as 
(
	select max(order_date) as latest_order_date
    from orders
),

customer_last_order as
(
		select customer_id,
        max(order_date) as last_order
        from orders
        where return_status ='Completed'
        group by customer_id
)

select
round(100*sum(case when datediff(m.latest_order_date, c.last_order)>180 then 1 else 0 end)/count(*), 2) 
as churn_rate_pct
from customer_last_order c
cross join max_order_date m;

-- CUSTOMER RETENTION RATE- WHO REMAINED ACTIVE DURING THE EVALUATION PERIOD
with max_order_date as
(
	select max(order_date) as latest_order_date
    from orders
),

active_customers as
( 	select count(distinct customer_id) as active_count
    from orders o
    cross join max_order_date m
    where o.return_status = 'Completed'
    and o.order_date >= date_sub(m.latest_order_date, interval 90 day)
),

total_customers as 
(		select count(*) as total_count
		from customers)
        
select
round((100 * a.active_count) / t.total_count, 2) as retention_rate_pct
from active_customers a
cross join total_customers t;